basePath: /api/v1
definitions:
  presentation.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  presentation.registerUserRequest:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - id
    - name
    - password
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:9091
info:
  contact:
    email: julio.perdiguer@gmail.com
    name: API Support
    url: https://julioperdiguer.es
  description: This is a Golang template API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang Template API
  version: "1.0"
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Registers a new user with the provided name, email, and password
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/presentation.registerUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/presentation.UserResponse'
        "400":
          description: 'Invalid input" example {"error": "invalid input"}'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Internal server error" example {"error": "internal server
            error"}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Registers a new user
      tags:
      - user
  /status:
    get:
      description: Provides the status of the service
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Provides the status of the service
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
