basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:9091
info:
  contact:
    email: julio.perdiguer@gmail.com
    name: API Support
    url: https://julioperdiguer.es
  description: This is a Golang template API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang Template API
  version: "1.0"
paths:
  /status:
    get:
      description: Provides the status of the service
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Provides the status of the service
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
