name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go '1.23.x'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Build
        run: go build ./cmd/api
      - name: Test with the Go CLI
        run: go test -v ./...
