# Use the official Golang base image
FROM golang:alpine AS build

RUN apk add --update git
# Set the working directory inside the container
WORKDIR /app

# Copy the Go application source code to the container
COPY . .

# Build the Go application
RUN go build -o main ./cmd/api

FROM scratch

COPY --from=build /app/main /app/main
# Expose the port that the application will run on
EXPOSE 9091
# Run the Go application
ENTRYPOINT ["/app/main"]
